CREATE TABLE IF NOT EXISTS categories(
    id SERIAL PRIMARY KEY NOT NULL,
    name VARCHAR(12) NOT NULL,
    user_id BIGINT REFERENCES users(id) NOT NULL,
    created_by BIGINT,
    updated_by BIGINT DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT NULL,
    deleted BOOLEAN DEFAULT FALSE NOT NULL
);